if(input$organism == 'Aotus nancymaae (Owl monkey)'){
  "cgagctgtggctgcgccatctgtcttcatcttccagccatctgaggaacaggtgaaatctggaactgcctctgttgtgtgcttgctgaatgacttctatcccagagatgtcagtgtcaagtggaaggtggatgacgtcgtccagtcgagtaacgtccaggacagtatcacagagcaggacagcaaggacaacacctacagcctcagcagcaccctgacgctgagcagcacagaataccagaggcacaaagtctacgcctgtgaggtcacccatcaaggcttgaactcgcccctcacgaagagcttccgtaaaggagagtgttag"
}else if(input$organism == 'Callithrix jacchus (Marmosets)'){
  "cgagctgtggctgcgccgtctgtcttcatcttcccgccatctgaggatcaggtgaaatctggaactgccactgttgtgtgcctactgaatggcttctatcccagagatgccaaggtaaagtggaaggtggatgatgtcgtccagtcggataacagtatccaggacagtatcacagagcaggacagcaaggacaacacctacagcctcagcagcaccttgacgctgagcagcacggaataccagaggcacaacgtctacgcctgtgaggtcacccatcagagcttgacctcgcccctcacgaagagcttccgtaaaggagagtgttag"
}else if(input$organism == 'Saimiri spp. (Squirrel monkey)'){
  "cgagctgtggctgcgccatccgtcttcatcttccagccatctgaggagcaggtgaaatctggaactgcctctcttgtgtgcatgctgaatggcttctatcccaaagatgtcaatgtgaagtggaaggtggatgacgtcgtccagccgaaggataacattcttgaaagtatcacagagcaggacagcaaggacaacacctacagcctcagcagcaccctgacgctgagcagcacagaataccagaggcacaacgtctacgcctgtgaggtcacccatcaaggcttgagatcgcccctcacgaagagcttccgtaaaggagagtgttag"
}