tabItem(tabName = "fedBatch",
        fluidRow(
          column(width = 3,
                 box(title = "Upload your data (xls file)",
                     width = NULL,
                     status = "primary",
                     fileInput(inputId = "stableData",
                               label = NULL,
                               accept = c(".xls")),
                     tags$a(href = "stableTestData.xls", "Download template", download=NA, target="_blank"),
                 ),
                 box(title = "Plotting parameters (y-axis)",
                     width = NULL,
                     status = "info",
                     radioButtons(
                       inputId = "dataplot",
                       label = NULL,
                       c('Titer (ug/ml)',
                         'Viable cell density (million/ml)',
                         'Viability (%)',
                         'pH',
                         'pO2 (mmHg)',
                         'pCO2 (mmHg)',
                         'Glutamine (mmol/L)',
                         'Glutamate (mmol/L)',
                         'Glucose (g/L)',
                         'Lactate (g/L)',
                         'Ammonium (mmol/L)',
                         'Sodium (mmol/L)',
                         'Potassium (mmol/L)'),
                     ),
                 ),
                 box(title = "Select plot theme",
                     width = NULL,
                     status = "info",
                     radioButtons(inputId = "plotTheme",
                                  label = NULL,
                                  c('Black & White (ggplot2)',
                                    'GraphPad Prism',
                                    'Default (ggplot2)')
                     ),
                 ),
                 downloadButton(outputId = "downloadStablePlot", label = "Download Plot"),
                 radioButtons(inputId = "var1", label = NULL, choices = list("png", "pdf", "svg", "tiff"), inline = TRUE)
                 # box(title = "Winning Clone",
                 #     width = NULL,
                 #     status = "success",
                 #     h4(textOutput("winClone")),
                 #     tags$style("#winClone{color: #339ACC; font-size: 30px; font-style: bold}"),
                 # ),
                 # box(title = "Max Titer (ug/ml)",
                 #     width = NULL,
                 #     status = "success",
                 #     h4(textOutput("maxTiter")),
                 #     tags$style("#maxTiter{color: #339ACC; font-size: 30px; font-style: bold}"),
                 # ),
                 # box(title = "Viability (%)",
                 #     width = NULL,
                 #     status = "success",
                 #     h4(textOutput("viab")),
                 #     tags$style("#viab{color: #339ACC; font-size: 30px; font-style: bold}"),
                 # ),
                 # box(title = "Final Day",
                 #     width = NULL,
                 #     status = "success",
                 #     h4(textOutput("finalDay")),
                 #     tags$style("#finalDay{color: #339ACC; font-size: 30px; font-style: bold}"),
                 # ),
                 
                 
          ),
          column(width = 9,
                 box(title = "Add Title to the Plot",
                     width = NULL,
                     status = "info",
                     textInput(inputId = "title2",
                               label = NULL,
                               placeholder = "Plot title"),
                 ),
                 box(title = "Add Subtitle to the Plot",
                     width = NULL,
                     status = "info",
                     textInput(inputId = "subtitle2",
                               label = NULL,
                               placeholder = "Plot subtitle"),
                 ),
                 box(title = "Fed Batch Plots",
                     width = NULL,
                     height = 500,
                     status = "primary",
                     plotOutput("stablePlot")
                 ),
                 
                 # downloadButton(outputId = "downloadStablePlot", label = "Download Plot"),
                 # radioButtons(inputId = "var1", label = NULL, choices = list("png", "pdf", "svg", "tiff"), inline = TRUE) 
                 
          )
        ),
        
)